from datetime import datetime
from sqlalchemy import BigInteger, String, ForeignKey, Integer, Boolean, DateTime, Float
from sqlalchemy.orm import relationship, Mapped, mapped_column
from app.configurations.dbconfig import SQL_BASE

# we are using SQL_BASE here because this model is part of the SQL Server
class StoreLocation(SQL_BASE):
    __tablename__ = 'StoreLocation'

    StoreLocationID: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    POSSystemCD: Mapped[str] = mapped_column(String(20), ForeignKey('POSSystem.POSSystemCD'), nullable=False)
    CompanyID: Mapped[int] = mapped_column(BigInteger, ForeignKey('Company.CompanyID'), nullable=False)
    PaymentSystemsProductCode: Mapped[int] = mapped_column(Integer, nullable=False)
    IsAutoPushToPOS: Mapped[bool] = mapped_column(Boolean, nullable=False)
    IsUploadToPOSEnabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    IsMixMatchEnabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    StoreFullName: Mapped[str] = mapped_column(String(100), nullable=False)
    StoreName: Mapped[str] = mapped_column(String(80))
    StoreAddressLine1: Mapped[str] = mapped_column(String(40))
    StoreAddressLine2: Mapped[str] = mapped_column(String(40))
    City: Mapped[str] = mapped_column(String(40))
    CountyCode: Mapped[str] = mapped_column(String(40))
    StateCode: Mapped[str] = mapped_column(String(2))
    PhoneNo: Mapped[str] = mapped_column(String(40))
    Fax: Mapped[str] = mapped_column(String(40))
    E_Mail: Mapped[str] = mapped_column(String(40))
    MacAddress: Mapped[str] = mapped_column(String(17), nullable=False)
    DownloadFilesLocation: Mapped[str] = mapped_column(String(500), nullable=False)
    StoreLocationIdentifier: Mapped[str] = mapped_column(String(50), unique=True)
    StoreContactName: Mapped[str] = mapped_column(String(50))
    NotificationE_Mail: Mapped[str] = mapped_column(String(40))
    NotificationSMSPhoneNo: Mapped[str] = mapped_column(String(66))
    LastPingFromClientDateTime: Mapped[datetime] = mapped_column(DateTime)
    SoftwareVersion: Mapped[str] = mapped_column(String(40))
    IsInvoiceEnabled: Mapped[bool] = mapped_column(Boolean, nullable=False)
    IsInPOSSyncStatus: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    LotteryStateCode: Mapped[str] = mapped_column(String(2))
    OtherAppMacAddress: Mapped[str] = mapped_column(String(100))
    InvoiceAppMacAddress: Mapped[str] = mapped_column(String(100))
    InvoiceAppUser: Mapped[str] = mapped_column(String(50))
    InvoiceAppPwd: Mapped[str] = mapped_column(String(50))
    IsFuelPriceUpdateEnabled: Mapped[bool] = mapped_column(Boolean, default=False)
    NoOfLotteryBins: Mapped[int] = mapped_column(Integer)
    IsDayCloseLocation: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    IsJobberOnly: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    ZIPCode: Mapped[str] = mapped_column(String(20))
    EnableDayReconSubmission: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    IsCOGEnabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    POSSystemSubCD: Mapped[str] = mapped_column(String(20), default='')
    LotteryRetailerID: Mapped[int] = mapped_column(Integer)
    LotteryRetailerPassword: Mapped[str] = mapped_column(String(50))
    LotteryRetailerUserName: Mapped[str] = mapped_column(String(50))
    POSStoreLocationID: Mapped[int] = mapped_column(Integer)
    IsLotteryStartingFromZero: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    IsPCLess: Mapped[bool] = mapped_column(Boolean)
    MNSPID: Mapped[int] = mapped_column(BigInteger)
    SiteIP: Mapped[str] = mapped_column(String(20))
    POSUsername: Mapped[str] = mapped_column(String(25))
    POSPassword: Mapped[str] = mapped_column(String(25))
    ServiceID: Mapped[str] = mapped_column(String(25))
    BaseVersion: Mapped[str] = mapped_column(String(25))
    Facebook: Mapped[str] = mapped_column(String(255))
    StoreLocationPosID: Mapped[int] = mapped_column(BigInteger)
    Website: Mapped[str] = mapped_column(String(255))
    TankMonitoringSystemID: Mapped[int] = mapped_column(BigInteger)
    siteProtocol: Mapped[str] = mapped_column(String(5), nullable=False, default='https')
    IsLotteryEnabled: Mapped[bool] = mapped_column(Boolean)
    Latitude: Mapped[float] = mapped_column(Float(precision=9, decimal_return_scale=6))
    Longitude: Mapped[float] = mapped_column(Float(precision=9, decimal_return_scale=6))

    # Fix: Use consistent relationship name
    company = relationship("Company", back_populates="store_locations")